name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake.svg
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      # Commit and push generated snake.svg to the main branch
      - name: Commit and push generated snake.svg
        run: |
          git config --global user.email "enstarunganesh@gmail.com"
          git config --global user.name "tarunganesh2004"
          git add dist/snake.svg
          git commit -m "Generated snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
